### PR TITLE
Add playlist panel to video player page

### LINKED ISSUE #216: UI Revamp: Playlist Video Player Page
This is a subtask of #165 

The "Playlist Video Player" page is where a video from a playlist can be viewed along with other videos in the playlist, by the user. The UI redesign for this page will be based on the following designs:

- Desktop View:

- Mobile View:

### PR DESCRIPTION
**Pull request by dan-niles**
This PR adds a playlist panel to the video player page.
- Added a playlist panel that displays the videos in a playlist (Playlist is loaded through the `list` query parameter in URL)
- Added player control buttons to loop (Loop video/playlist) and shuffle playlist.
- Updated error handling for unknown videos, playlists and paths.

Screenshot:
image

Closes #216

### CODE REVIEW

**Review by benoit74 — COMMENTED** [review]
Looks good, works well, thank you!

Only a small interrogation. I'm not familiar at all with the `nextTick` API, and I fail to find examples on the net on how to use this properly. Do we really need the two calls to `nextTick`, once in the `watch` and once in the method itself?

**Comment by benoit74** [comment]
Maybe one question for @Popolechien: we have a setting at ZIM level regarding autoplay, which is used to decide if we want to autoplay the video every time a page is opened. By default, it is off.

However, with the new UI in playlist mode we will now automatically move from one video to the next when the video is over. Do we still want to take into account the autoplay setting? I.e. if autoplay setting is false, when a video finishes, the UI moves automatically to the next video but video does not start. Or do we want to always start the next video automatically in such a situation?

**Comment by Popolechien** [comment]
What does Youtube do? Unless we can make a compelling argument that our users are different from theirs, we should mimic YT's behaviour as much as possible (which may, at times, include things we at a personal level do not particularly enjoy).

Autoplay it is, then.

**Comment by benoit74** [comment]
Agreed.

Does it means we do not really need the "autoplay" setting at scraper level and could even imagine to get rid of it? Do you recall when / why it was introduced? I imagine it could be to save bandwidth (avoid loading the video if the user finally decides he does not want to see it) but I'm not sure it makes lot of sense in terms of usability.

**Comment by Popolechien** [comment]
> Do you recall when / why it was introduced?

I think you wildly overestimate my technical involvement or even my ability to understand why certain technical choices are made. But thank you for that :-) 

I am pretty sure I don't understand the difference between autoplay and autoplay at scraper level, so I'll focus on the end result and simply ask that things, well, _autoplay_.

**Comment by dan-niles** [comment]
> Only a small interrogation. I'm not familiar at all with the `nextTick` API, and I fail to find examples on the net on how to use this properly. Do we really need the two calls to `nextTick`, once in the `watch` and once in the method itself?

@benoit74 Oops that's a mistake. Thanks for pointing it out. I must have duplicated it when doing some debugging and forgot to remove it. Removed it in [59b89cd](https://github.com/openzim/youtube/pull/237/commits/59b89cd3f3fa30754d98a5ce0dab11f40faa2802).

[nextTick()](https://vuejs.org/api/general.html#nexttick) is used so that the scrolling in the playlist panel happens after the DOM updates for loading the video are completed.

**Comment by dan-niles** [comment]
If there is anything else to fix please let me know or else I can squash and rebase. Should I remove the `--autoplay` argument and make autoplay always true? or do we create a seperate issue for this?

**Comment by benoit74** [comment]
> If there is anything else to fix please let me know or else I can squash and rebase. 

Please squash and rebase

> Should I remove the --autoplay argument and make autoplay always true? or do we create a seperate issue for this?

Please update https://github.com/openzim/youtube/issues/233 by changing title and add a new comment saying that we've finally decided to `autoplay: true` and remove CLI argument, referring to the discussion in this PR. And do the change in other PR for clarity.

**Review by benoit74 — APPROVED** [review]
LGTM, please squash and rebase

**Comment by dan-niles** [comment]
Squash and rebase completed

**Review by benoit74 — CHANGES_REQUESTED** [review]
Looks like rebase is not finished, your branch is still not on top of `main` latest commit

**Review by benoit74 — APPROVED** [review]
LGTM, thank you

**Pull request merged**
