### PR TITLE
requirements.txt: zimscraperlib>=2.0.0,<2.1.0

### PR DESCRIPTION
**Pull request by holta**
Thanks to @deldesir who quickly tested this with zimscraperlib 2.0.0

@rgaudin & @kelson42 is this what's needed?

- #171

### CODE REVIEW

**Review by rgaudin — CHANGES_REQUESTED** [review]
The idea is to bump is to the version you want to use yet define a range to allow for its future minor versions to be used.
So it would be:

```
zimscraperlib>=2.0.0,<2.1.0
```

**Comment by holta** [comment]
> The idea is to bump is to the version you want to use yet define a range to allow for its future [PATCH] versions to be used.

I assume you mean PATCH versions rather than MINOR, per https://semver.org/#semantic-versioning-200

Done!

**Review by rgaudin — APPROVED** [review]
LGTM

**Comment by rgaudin** [comment]
Yes, sorry 😉

**Pull request merged**
